// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/supermarios-hotel-management-system/authentication/model"

	time "time"
)

// MockAuthenticationSessionRepository is an autogenerated mock type for the AuthenticationSessionRepository type
type MockAuthenticationSessionRepository struct {
	mock.Mock
}

type MockAuthenticationSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticationSessionRepository) EXPECT() *MockAuthenticationSessionRepository_Expecter {
	return &MockAuthenticationSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, userID, refreshToken, expiresAt
func (_m *MockAuthenticationSessionRepository) CreateSession(ctx context.Context, userID uint64, refreshToken string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, refreshToken, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, time.Time) error); ok {
		r0 = rf(ctx, userID, refreshToken, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthenticationSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockAuthenticationSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - refreshToken string
//   - expiresAt time.Time
func (_e *MockAuthenticationSessionRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, refreshToken interface{}, expiresAt interface{}) *MockAuthenticationSessionRepository_CreateSession_Call {
	return &MockAuthenticationSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, refreshToken, expiresAt)}
}

func (_c *MockAuthenticationSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uint64, refreshToken string, expiresAt time.Time)) *MockAuthenticationSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockAuthenticationSessionRepository_CreateSession_Call) Return(_a0 error) *MockAuthenticationSessionRepository_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticationSessionRepository_CreateSession_Call) RunAndReturn(run func(context.Context, uint64, string, time.Time) error) *MockAuthenticationSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSessionByRefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthenticationSessionRepository) GetActiveSessionByRefreshToken(ctx context.Context, refreshToken string) (*model.AuthenticationSession, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSessionByRefreshToken")
	}

	var r0 *model.AuthenticationSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AuthenticationSession, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AuthenticationSession); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthenticationSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSessionByRefreshToken'
type MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call struct {
	*mock.Call
}

// GetActiveSessionByRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthenticationSessionRepository_Expecter) GetActiveSessionByRefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call {
	return &MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call{Call: _e.mock.On("GetActiveSessionByRefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call) Return(_a0 *model.AuthenticationSession, _a1 error) *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*model.AuthenticationSession, error)) *MockAuthenticationSessionRepository_GetActiveSessionByRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSessionByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAuthenticationSessionRepository) GetActiveSessionByUserID(ctx context.Context, userID uint64) ([]*model.AuthenticationSession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSessionByUserID")
	}

	var r0 []*model.AuthenticationSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*model.AuthenticationSession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*model.AuthenticationSession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AuthenticationSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSessionByUserID'
type MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call struct {
	*mock.Call
}

// GetActiveSessionByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockAuthenticationSessionRepository_Expecter) GetActiveSessionByUserID(ctx interface{}, userID interface{}) *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call {
	return &MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call{Call: _e.mock.On("GetActiveSessionByUserID", ctx, userID)}
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call) Return(_a0 []*model.AuthenticationSession, _a1 error) *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call) RunAndReturn(run func(context.Context, uint64) ([]*model.AuthenticationSession, error)) *MockAuthenticationSessionRepository_GetActiveSessionByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, sessionID
func (_m *MockAuthenticationSessionRepository) RevokeSession(ctx context.Context, sessionID uint64) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthenticationSessionRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockAuthenticationSessionRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uint64
func (_e *MockAuthenticationSessionRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}) *MockAuthenticationSessionRepository_RevokeSession_Call {
	return &MockAuthenticationSessionRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *MockAuthenticationSessionRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID uint64)) *MockAuthenticationSessionRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuthenticationSessionRepository_RevokeSession_Call) Return(_a0 error) *MockAuthenticationSessionRepository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticationSessionRepository_RevokeSession_Call) RunAndReturn(run func(context.Context, uint64) error) *MockAuthenticationSessionRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticationSessionRepository creates a new instance of MockAuthenticationSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticationSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticationSessionRepository {
	mock := &MockAuthenticationSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
